matrix:
  include:
    # linux
    - os: linux
      env: 
        - BUILD_TARGET=linux 
        - GEN_BINDING_AND_COCOSFILE=true
        - secure: oKSlzGHaDebDYMJdvAOG6dH2syKUiog3oxpRWM060ywPhG8Zs6XyOgun6VnRi89gkkAB4Vp4IQaZ2J3f1+0pQTJcs9fii1aG/G5IemXMJrNIp2doJTXzQ0jhsBMubDhWKet2RK+Y9saOirQHf1IOLoZXSLJhZ04ZEQkDoY48Ev0=
        - secure: LO5Bo6yecMQBMtTE/JmUinUejeiYDz0ubTLRxSnOc307ItwZzCaVvY2ugTUYORW9wrhI3NMp0u/CmNJNS1g3/G/qUrkCFPZ94LRdmLyp1Gm5Vn0tHIUw3Lr8fLi+6FNZxaRX4L4i8OuJH7KvICILCXOLDSDWVjDQF5bysn6NaEM=
        - secure: WamDtUxG+H+9TALHfxIUtDgRvtTdI7X31cH16FW4FFitdsFTo/GtubDKhvhd8jaMtpqmQ7FOTtn/gXCngP4USliuMjP8zYUkSaogJ039dFLXbNuPXUwA8dynmerolr35kUiqjXTv0zVakUbNeNHprBwj8+f10I+foxSst6hxCFs=
      language: cpp
      sudo: required
      addons:
        apt:
          sources:
            - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
          packages:
            - cmake
            - cmake-data
    # android
    - os: linux
      env: BUILD_TARGET=android
      language: android
      sudo: required
      android:
        components:
          - android-10
    # mac lua-tests + js-tests
    - os: osx
      env: BUILD_TARGET=mac
      language: cpp
      osx_image: xcode7.3
      sudo: required
      python:
        - "2.7"
      cache: pip
    # mac cpp-tests
    - os: osx
      env: BUILD_TARGET=mac BUILD_CPP=true
      language: cpp
      osx_image: xcode7.3
      sudo: required
      python:
        - "2.7"
      cache: pip
    # iOS lua-tests + js-tests
    - os: osx
      env: BUILD_TARGET=ios
      language: cpp
      osx_image: xcode7.3
      sudo: required
      python:
        - "2.7"
      cache: pip
    # iOS cpp-tests
    - os: osx
      env: BUILD_TARGET=ios BUILD_CPP=true
      language: cpp
      osx_image: xcode7.3
      sudo: required
      python:
        - "2.7"
      cache: pip

script:
- tools/travis-scripts/run-script.sh
before_install:
- tools/travis-scripts/before-install.sh

cache:
  bundler: true

notifications:
  email: false

# blocklist
branches:
  except:
  - v1
  - v2
  - v4-develop
  - v3-doc
  - v3.11_backup
  - v35-for-tizen
